In [2]:
import numpy as np

In [2]:
a = np.array(0)
a, a.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [3]:
a = np.array([2, 4, 6])
a, a.ndim, type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [4]:
a = np.array( [[1,2,3], [4,5,6]] )
a, a.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [5]:
a = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ] )
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

In [6]:
a = np.array(3)
a, a.shape # 행렬아님

(array(3), ())

In [7]:
a = np.array([ 1, 3, 5, 7, 9 ])
a, a.shape

(array([1, 3, 5, 7, 9]), (5,))

In [8]:
a = np.array([[1,2,3], [4,5,6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [9]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

In [10]:
a= np.array([1, 3, 5, 7, 9])
a.size

5

In [11]:
a = np.array([[1,2,3], [4,5,6]])
a.size

6

In [13]:
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [14]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape} 구조타입={type(myArr.shape)}, size={myArr.size}')


[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,) 구조타입=<class 'tuple'>, size=5


In [15]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [16]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape} 구조타입 = {type(myArr2.shape)}, size = {myArr2.size}')

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3) 구조타입 = <class 'tuple'>, size = 9


In [17]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4 ],[10,20 ,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [18]:
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape} 구조타입 = {type(myArr21.shape)}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [19]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

[10, 30, 50, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [20]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

[10, 30, 50, 10, 30, 50]


TypeError: can't multiply sequence by non-int of type 'list'

In [21]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [22]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


In [ ]:
test = [[1,2,3],[1,2]]

In [32]:
arr = [[1,2,3],[1,2,"데이터"]]
arr2 = arr = [[1,2,3],[1,2,"데이터"]]
# 비어있는 값을 넣는다 null

In [33]:
myArray = np.array(arr)
yourArray = np.array(arr2)
print(f'차원= {myArray.ndim}, 구조 = {myArray.shape} 구조타입 = {type(myArray.shape)}, size = {myArray.size}')



차원= 2, 구조 = (2, 3) 구조타입 = <class 'tuple'>, size = 6


In [46]:
print(myArray)
#myArray

[['1' '2' '3']
 ['1' '2' '데이터']]


In [1]:
myList21 = [ [1,2,3,4 ],[10,20 ,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [4]:
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape} 구조타입 = {type(myArr21.shape)}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [24]:
"epdlxj" + "데이터"

'epdlxj데이터'

In [29]:
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

['안녕', 100, 3.14, True, False]


In [31]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환
print(myArr_c, type(myArr_c), myArr_c.dtype)
myArr_c

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


array(['안녕', '100', '3.14', 'True', 'False'], dtype='<U32')

In [36]:
test = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17,18, 19, 20], [21, 22, 23, 24]]])

In [45]:
test[1]

24

In [4]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\Pee\AppData\Local\Temp\ipykernel_21724\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\Pee\AppData\Local\Temp\ipykernel_21724\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [5]:
np.log(0)

C:\Users\Pee\AppData\Local\Temp\ipykernel_21724\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [6]:
np.exp(-np.inf)

0.0

In [7]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [8]:
np.mean(x)

4.8076923076923075

In [9]:
np.var(x)

115.23224852071006

In [10]:
np.std(x)

10.734628476137871

In [11]:
np.max(x)

23

In [12]:
np.min(x)

-24

In [13]:
np.median(x)

5.0

In [14]:
np.percentile(x, 0)

-24.0

In [15]:
np.percentile(x, 25)

0.0

In [16]:
np.percentile(x, 50)

5.0

In [17]:
np.percentile(x, 75)

10.0

In [19]:
np.percentile(x, 100)

23.0

In [20]:
print(np.ones(10), np.ones(10).dtype) 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [22]:
print(np.ones((2,4,6)), np.ones((2,4)).dtype)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]] float64


In [23]:
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [24]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [25]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [36]:
np.zeros(30).reshape(2,3,5).flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros(30).reshape(2,3,5).reshape(-1,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.arange(1,21).reshape(5,4).reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [42]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [43]:
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [44]:
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [ ]:
num= np.arange(1,47)
np.random.shuffle(num)
num[:6]

In [46]:
np.random.randint(1,46,6)

array([18, 27,  1,  6, 28, 16])

In [47]:
np.empty(10)

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [48]:
print(np.ones(10), np.ones(10).dtype) 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [49]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [64]:
arr = np.arange(1,21).reshape(2,2,5)
arr.dtype #얘를 float64로 바꾸려면?
arr1 = arr.astype(np.float64)
arr1.dtype
arr2 = arr1.astype("<U5")
arr2

array([[['1.0', '2.0', '3.0', '4.0', '5.0'],
        ['6.0', '7.0', '8.0', '9.0', '10.0']],

       [['11.0', '12.0', '13.0', '14.0', '15.0'],
        ['16.0', '17.0', '18.0', '19.0', '20.0']]], dtype='<U5')

In [66]:
arr = np.array([
                [10, 11, 12, 13, 14],
                [15, 16, 17, 18, 19],
                [20, 21, 22, 23, 24]
               ])

In [80]:
arr[::-1, ::]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])

In [90]:
arr = np.array( [
                [ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]
                ])

In [107]:
arr[::-1, 4:1:-1]

array([[25, 24, 23],
       [20, 19, 18],
       [15, 14, 13],
       [10,  9,  8],
       [ 5,  4,  3]])

In [128]:
arr = np.random.randint(3,60,(4,6))
arr

array([[ 9,  5, 13, 14, 24, 54],
       [23, 53, 23, 54, 45, 22],
       [26, 23, 19, 24, 11, 22],
       [ 5,  4,  3,  9, 21, 43]])

In [135]:
np.sort(arr,axis=1)[::, ::-1]

array([[54, 24],
       [54, 53],
       [26, 24],
       [43, 21]])

In [ ]:
np.sum(m1[0,:], axis=0) # x축(행 방향) 합계

In [3]:
arr = np.array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])
arr

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [6]:
arr.shape[1]

4

In [7]:
arr = np.array([[100,   1,   2,   3,4],
       [200,   4,   5,   6,5],
       [300,   7,   8,   9,10]])
arr

array([[100,   1,   2,   3,   4],
       [200,   4,   5,   6,   5],
       [300,   7,   8,   9,  10]])

In [10]:
arr.shape[1]

5

In [11]:
np.insert(arr, arr.shape[1], [1000,2000,3000], axis=1)

array([[ 100,    1,    2,    3,    4, 1000],
       [ 200,    4,    5,    6,    5, 2000],
       [ 300,    7,    8,    9,   10, 3000]])

In [25]:
arr

array([[100,   1,   2,   3,   4],
       [200,   4,   5,   6,   5],
       [300,   7,   8,   9,  10]])

In [30]:
arr = np.delete(arr,0,axis=1)
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9, 10]])

In [33]:
arr = np.arange(1, 21)

In [40]:
arr[(arr > 10) & (arr < 15)]

array([11, 12, 13, 14])

In [42]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
arr[[0,3,5]]

array([10, 13, 15])

In [48]:
np.where((arr>15)&(arr<18),arr*2,arr)

array([10, 11, 12, 13, 14, 15, 32, 34, 18, 19])